name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  RELOADEDIIMODS: .

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize Git Submodules
        run: git submodule update --init --recursive

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build project (Release)
        run: dotnet publish BGME.Framework -c Release -o Release/BGME.Framework /p:OutputPath=BGME.Framework/output

      - name: Zip folder
        run: Compress-Archive -Path Release/BGME.Framework -DestinationPath BGME.Framework.zip

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: BGME.Framework.zip
          fail_on_unmatched_files: true